In [209]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set_style('whitegrid')

In [210]:
df = pd.read_excel('racist_dataset.xlsx');
df = df.dropna();

In [211]:
col_name = ['comment', 'label']
df.columns = col_name
df.head()

comment  label
0  තම්බි දැනගනිල්ලා. යකෝ හමුදුරුවෝ හදන්නේ මෙක අවු...      1
1  මුස්ලිම් ආගම ස්භාව දහමටත් මනුෂ්‍යත්වයටත් විරැද...      1
2  අපිට මේ සිද්දියෙන් පිලිතුරක් ඔනේ මුස්ලිම් ආගම ...      1
3         තම්බි කෙලොගන්න හදන්නෙ...කට පියාගන හිටපියව්      1
5  ඔහොම හරියන්නෙ නෑ තම්බි ටික සමූල ගාතනයක් කරමු උ...      1

In [212]:
from sklearn.model_selection import train_test_split

In [213]:
X = df['comment'].str.strip();
y = df['label'];

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=9)

## Using NGRAM

In [214]:
from sklearn.feature_extraction.text import CountVectorizer

# If you want to take into account just term frequencies:
vectorizer = CountVectorizer(ngram_range=(1, 2))
# The ngram range specifies your ngram configuration.

X_train_ngram = vectorizer.fit_transform(X_train)
# Testing the ngram generation:
#print(vectorizer.get_feature_names())
# This will print: ['by car', 'by jack', 'car was', 'cleaned by', 'jack was', 'was cleaned']

#print(X.toarray())
# This will print:[[0 1 1 1 0 1], [1 0 0 1 1 1]]

X_train_arr = X_train_ngram.toarray();

In [215]:
X_test_ngram = vectorizer.transform(X_test) 
X_test_arr = X_test_ngram.toarray()

In [216]:
from sklearn import svm

In [217]:
C = 0.7
clf = svm.SVC(kernel='linear', C=C)

In [218]:
clf.fit(X_train_arr, y_train)

SVC(C=0.7, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [219]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

In [220]:
res = cross_val_score(clf, X_train_arr, y_train, cv=10, scoring='accuracy')
print('Average Accuarcy: \t {0:.4f}'.format(np.mean(res)))
print('Accuarcy SD: \t\t {0:.4f}'.format(np.std(res)))

Average Accuarcy: 	 0.7623
Accuarcy SD: 		 0.1281


In [221]:
y_train_pred = cross_val_predict(clf, X_train_arr, y_train, cv=3)

In [222]:
confusion_matrix(y_train, y_train_pred)

array([[95,  7],
       [34, 29]])

In [223]:
print('Precision score: \t {0:0.4f}'.format(precision_score(y_train, 
                                                          y_train_pred, 
                                                          average='weighted')))
print('Recall score: \t {0:0.4f}'.format(recall_score(y_train, 
                                                          y_train_pred, 
                                                          average='weighted')))
print('F1 score: \t {0:0.4f}'.format(f1_score(y_train, 
                                                          y_train_pred, 
                                                          average='weighted')))

Precision score: 	 0.7628
Recall score: 	 0.7515
F1 score: 	 0.7322


In [224]:
y_test_pred = cross_val_predict(clf, X_test_arr, y_test, cv=3)

In [225]:
confusion_matrix(y_test, y_test_pred)

array([[31,  5],
       [14, 21]])

In [226]:
print('Precision score: \t {0:0.4f}'.format(precision_score(y_test, 
                                               y_test_pred)))
print('Recall score: \t {0:0.4f}'.format(recall_score(y_test, 
                                             y_test_pred)))
print('F1 score: \t {0:0.4f}'.format(f1_score(y_test, 
                                             y_test_pred)))

Precision score: 	 0.8077
Recall score: 	 0.6000
F1 score: 	 0.6885


In [227]:
# review = np.array(['ගෙරි හම්බයා'])
# review = np.array(['ඒ උනාට සිංහල නෑනෙ'])
# review = np.array(['ඉල්ලන දෙයක් දෙන්නම් මට සහය දෙන්න'])
# review = np.array(['සිංහල'])
review = np.array(['ඔහොම හරියන්නෙ නෑ තම්බි ටික සමූල ගාතනයක් කරමු'])

review.reshape(-1, 1)

res = clf.predict(vectorizer.transform(review).toarray())

if (res == 1):
    print('Hate')
else:
    print('Non hate')    

Hate


## Using TF-IDF with NGRAM (With normalization)

In [228]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [229]:
## And now testing TFIDF vectorizer:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), norm=None) # You can still specify n-grams here.
X_train_vec = vectorizer.fit_transform(X_train)

In [230]:
X_test_vec = vectorizer.transform(X_test)

In [231]:
from sklearn import svm

In [232]:
C = 0.7
clf = svm.SVC(kernel='linear', C=C)

In [233]:
clf.fit(X_train_vec, y_train)

SVC(C=0.7, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [234]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

In [235]:
res = cross_val_score(clf, X_train_vec, y_train, cv=10, scoring='accuracy')
print('Average Accuarcy: \t {0:.4f}'.format(np.mean(res)))
print('Accuarcy SD: \t\t {0:.4f}'.format(np.std(res)))

Average Accuarcy: 	 0.7331
Accuarcy SD: 		 0.0842


In [236]:
y_train_pred = cross_val_predict(clf, X_train_vec, y_train, cv=3)

In [237]:
confusion_matrix(y_train, y_train_pred)

array([[96,  6],
       [40, 23]])

In [238]:
print('Precision score: \t {0:0.4f}'.format(precision_score(y_train, 
                                                          y_train_pred, 
                                                          average='weighted')))
print('Recall score: \t {0:0.4f}'.format(recall_score(y_train, 
                                                          y_train_pred, 
                                                          average='weighted')))
print('F1 score: \t {0:0.4f}'.format(f1_score(y_train, 
                                                          y_train_pred, 
                                                          average='weighted')))

Precision score: 	 0.7392
Recall score: 	 0.7212
F1 score: 	 0.6896


In [239]:
y_test_pred = cross_val_predict(clf, X_test_vec, y_test, cv=3)

In [240]:
confusion_matrix(y_test, y_test_pred)

array([[32,  4],
       [20, 15]])

In [241]:
print('Precision score: \t {0:0.4f}'.format(precision_score(y_test, 
                                               y_test_pred)))
print('Recall score: \t {0:0.4f}'.format(recall_score(y_test, 
                                             y_test_pred)))
print('F1 score: \t {0:0.4f}'.format(f1_score(y_test, 
                                             y_test_pred)))

Precision score: 	 0.7895
Recall score: 	 0.4286
F1 score: 	 0.5556


In [242]:
# review = np.array(['ගෙරි හම්බයා'])
# review = np.array(['ඒ උනාට සිංහල නෑනෙ'])
# review = np.array(['ඉල්ලන දෙයක් දෙන්නම් මට සහය දෙන්න'])
# review = np.array(['සිංහල'])
review = np.array(['ඔහොම හරියන්නෙ නෑ තම්බි ටික සමූල ගාතනයක් කරමු'])

review.reshape(-1, 1)

res = clf.predict(vectorizer.transform(review))

if (res == 1):
    print('Hate')
else:
    print('Non hate')

Hate
